{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.service }}
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccountRef.name }}
            namespace: {{ .Values.secretStore.serviceAccountRef.namespace }}
{{- end }}
