{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $svc.namespace }}
  labels:
{{ include "togglemaster.labels" $ | indent 4 }}
    app: {{ $svc.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $svc.name }}
  ports:
    - name: http
      port: {{ $svc.servicePort }}
      targetPort: {{ $svc.containerPort }}
{{- end }}
{{- end }}
