{{- range $name, $sa := .Values.serviceAccounts }}
{{- if $sa.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ $sa.namespace }}
  labels:
{{ include "togglemaster.labels" $ | indent 4 }}
  {{- with $sa.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
