namespaces:
  create: false
serviceAccounts:
  analytics:
    create: true
  evaluation:
    create: false
services:
  auth:
    enabled: false
  flag:
    enabled: false
  targeting:
    enabled: false
  evaluation:
    enabled: false
  analytics:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/analytics-service
      tag: v0.47.0-17ed635
      digest: sha256:3e6a358ab25f211c3a87d27f980a9d085909e45599e80220ea7a1f2aac34f47a
gateway:
  enabled: false
keda:
  analytics:
    enabled: true
