namespaces:
  create: false
secretStore:
  enabled: true
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: false
services:
  auth:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/auth-service
      tag: v0.64.0
      digest: sha256:f555a80f832ef71fcd20a8673ac905d6fd70909710676fb26b1dd5bdd5ba0542
  flag:
    enabled: false
  targeting:
    enabled: false
  evaluation:
    enabled: false
  analytics:
    enabled: false
gateway:
  enabled: false
