namespaces:
  create: false
secretStore:
  enabled: true
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: false
services:
  auth:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/auth-service
      tag: v0.60.0
      digest: sha256:7d5a09f3d1dec48af4bb7491f54b6d5e5cf5ed4929510ee41a523d957a2994a5
  flag:
    enabled: false
  targeting:
    enabled: false
  evaluation:
    enabled: false
  analytics:
    enabled: false
gateway:
  enabled: false
