namespaces:
  create: false
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: true
services:
  auth:
    enabled: false
  flag:
    enabled: false
  targeting:
    enabled: false
  evaluation:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/evaluation-service
      tag: v0.57.0-2853621
      digest: sha256:305c7165c3446c5ac18d6f5bc8de93949b2ebc554b892226bc22f81f112bd8f6
  analytics:
    enabled: false
gateway:
  enabled: false
autoscaling:
  evaluation:
    enabled: true
