namespaces:
  create: false
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: true
services:
  auth:
    enabled: false
  flag:
    enabled: false
  targeting:
    enabled: false
  evaluation:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/evaluation-service
      tag: v0.51.0
      digest: sha256:91c895153934ec3da69309dc162716d5458723d0156607e5f92e219f4b6c96c4
  analytics:
    enabled: false
gateway:
  enabled: false
autoscaling:
  evaluation:
    enabled: true
