namespaces:
  create: false

serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: false

services:
  auth:
    enabled: false
  flag:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/flag-service
      tag: v0.1.0
  targeting:
    enabled: false
  evaluation:
    enabled: false
  analytics:
    enabled: false

gateway:
  enabled: false