namespaces:
  create: false
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: false
services:
  auth:
    enabled: false
  flag:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/flag-service
      tag: v0.57.0-2853621
      digest: sha256:b2ceb802668822274ccf591b5eb54a12c7ba5850b5b2905485e4dcdf428b81db
  targeting:
    enabled: false
  evaluation:
    enabled: false
  analytics:
    enabled: false
gateway:
  enabled: false
