namespaces:
  create: false
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: false
services:
  auth:
    enabled: false
  flag:
    enabled: false
  targeting:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/targeting-service
      tag: v0.52.0
      digest: sha256:ffa2005c6de98e670b76fae7c9a59e2dda8f674a3dd305c4a30069e3666493c7
  evaluation:
    enabled: false
  analytics:
    enabled: false
gateway:
  enabled: false
