namespaces:
  create: false
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: false
services:
  auth:
    enabled: false
  flag:
    enabled: false
  targeting:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/targeting-service
      tag: v0.48.0-17ed635
      digest: sha256:94c8e5fe634290e7b827ca6e7aa9313f113af5f1f19c21895fa7848a6751ef50
  evaluation:
    enabled: false
  analytics:
    enabled: false
gateway:
  enabled: false
