namespaces:
  create: false
serviceAccounts:
  analytics:
    create: false
  evaluation:
    create: false
services:
  auth:
    enabled: false
  flag:
    enabled: false
  targeting:
    enabled: true
    image:
      repository: 927738510198.dkr.ecr.us-east-1.amazonaws.com/togglemaster-dev/targeting-service
      tag: v0.55.0
      digest: sha256:a24015d6c6885bf5143367730f8defa9a57c83e1b707c53c0ec168f179581c4b
  evaluation:
    enabled: false
  analytics:
    enabled: false
gateway:
  enabled: false
